language: java

jdk:
  - oraclejdk8

env:
  global:
    - CODECOV_TOKEN="6163254c-13cf-4c97-8741-350f29632ef2"
    - COVERALLS_REPO_TOKEN=iCjm0mrwuJy7FNdAyfXXHXkSxzwHuVuOS
    - CI_NAME=travis-ci

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

install:
  - ./gradlew clean dependencies

script:
  - ./gradlew compileJava compileTestJava
  - ./gradlew check unitTest endToEndTest pitest
  - ./gradlew assemble

after_success:
  - ./gradlew jacocoTestReport coveralls
